#!/usr/bin/env python
# -*- coding: utf-8 -*-

import sys

from rqt_testpkg.my_module import MyPlugin
from rqt_gui.main import Main

plugin = 'rqt_testpkg'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))
